name: 'Get Project Code Changes'
description: 'Returns which apps and libraries have been modified in a PR'
outputs:
  affected_apps:
    description: Names of the affected apps
    value: ${{ steps.affected-apps.outputs.changes }}
  affected_libs:
    description: Names of the affected libs
    value: ${{ steps.affected-libs.outputs.changes }}
runs:
  using: 'composite'
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Cache node_modules
      uses: ./.github/actions/cache-node-modules
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v2
    - name: Get affected apps
      id: affected-apps
      run: changes="[\"$(yarn nx affected:apps --plain | sed -e "s/ /\",\"/g")\"]" && echo "::set-output name=changes::$changes"
      shell: bash
    - name: Get affected libs
      id: affected-libs
      run: changes="[\"$(yarn nx affected:libs --plain | sed -e "s/ /\",\"/g")\"]" && echo "::set-output name=changes::$changes"
      shell: bash
